/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.64.1
  Forc version: 0.46.1
  Fuel-Core version: 0.20.7
*/

export type { PainterContractAbi } from './PainterContractAbi';

export { PainterContractAbi__factory } from './factories/PainterContractAbi__factory';
